// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCawoE7uOltadfHPHE16C7m3rZ2TQdKZR0',
    appId: '1:268425098580:web:9b8e23be576c77743204c1',
    messagingSenderId: '268425098580',
    projectId: 'smart-hospital-7a180',
    authDomain: 'smart-hospital-7a180.firebaseapp.com',
    databaseURL: 'https://smart-hospital-7a180-default-rtdb.firebaseio.com',
    storageBucket: 'smart-hospital-7a180.appspot.com',
    measurementId: 'G-45QJMWX2XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5RTrmJuBvxq_JLfEM2mOcEXe28VBl_6g',
    appId: '1:268425098580:android:2647d38b71aafb953204c1',
    messagingSenderId: '268425098580',
    projectId: 'smart-hospital-7a180',
    databaseURL: 'https://smart-hospital-7a180-default-rtdb.firebaseio.com',
    storageBucket: 'smart-hospital-7a180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxzDr9jtjfEvFQ66n0MAgzgEJApcqE-OU',
    appId: '1:268425098580:ios:244ffabd56f03b613204c1',
    messagingSenderId: '268425098580',
    projectId: 'smart-hospital-7a180',
    databaseURL: 'https://smart-hospital-7a180-default-rtdb.firebaseio.com',
    storageBucket: 'smart-hospital-7a180.appspot.com',
    iosBundleId: 'com.example.smartHospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxzDr9jtjfEvFQ66n0MAgzgEJApcqE-OU',
    appId: '1:268425098580:ios:da16b83ba5fcbad53204c1',
    messagingSenderId: '268425098580',
    projectId: 'smart-hospital-7a180',
    databaseURL: 'https://smart-hospital-7a180-default-rtdb.firebaseio.com',
    storageBucket: 'smart-hospital-7a180.appspot.com',
    iosBundleId: 'com.example.smartHospital.RunnerTests',
  );
}
